exclude = [
    ".git",
    ".ruff_cache",
    "data",
    "logs",
    "wandb",
]

line-length = 128
indent-width = 4

target-version = "py312"

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[lint.pydocstyle]
convention = "google"

[lint]

preview = true

allowed-confusables = ["ρ", "×", "–", "γ"]

select = [
  "A", "E", "F", "B", "W",
  "C4", "EXE", "PIE", "repeated-equality-comparison", "ARG",
  "PERF", "FURB",  "PLE",
  "RUF", "SIM", "NPY", "FBT",
#"COM",
#"RET",
#"PLR",
#"S", "EM", "TRY", "BLE",  # exceptions
#"Q", # quotes
#"FIX", "TD", "ERA",
]
ignore = [
  "bare-except",
  "undocumented-magic-method",
  "numpy-legacy-random",
  "ambiguous-variable-name",
  "line-too-long",
  'too-many-branches',
  'too-many-arguments',
  'too-many-locals',
  'too-many-positional-arguments',
  'too-many-nested-blocks',
  "unnecessary-collection-call",
# whitespaces
  "whitespace-after-open-bracket", "whitespace-before-close-bracket",
  "whitespace-before-punctuation", "whitespace-before-parameters",
  "multiple-spaces-before-operator", "multiple-spaces-after-operator",
  "missing-whitespace-around-operator", "missing-whitespace-around-arithmetic-operator", "missing-whitespace-around-bitwise-or-shift-operator", "missing-whitespace-around-modulo-operator",
  "missing-whitespace", "multiple-spaces-after-comma",
  "multiple-spaces-after-keyword", "multiple-spaces-before-keyword",
  "no-space-after-block-comment",
# SIM
  "if-else-block-instead-of-if-exp",
  "suppressible-exception",
  "open-file-with-context-handler",
]


[lint.per-file-ignores]
"process/dataloader.py" = ["unused-method-argument", "float-equality-comparison"]
"process/dataloader_test.py" = ["unused-method-argument"]

